version: '3'
services:
  mf:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8345:8345"
    depends_on:
      - db
  
  db:
    image: postgres:9.6.10
    restart: always
    environment:
      POSTGRES_PASSWORD: smartarjan01
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:  
